kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: product-service
    app.kubernetes.io/component: product-service
    app.kubernetes.io/instance: product-service
    app.kubernetes.io/part-of: product-service-app
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - product-service
        from:
          kind: ImageStreamTag
          name: 'product-service:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: product-service
    deploymentconfig: product-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-service
        deploymentconfig: product-service
        {{ if .Values.use_preset }}
        ca-bundle-type: rhel-python
        {{ end }}
    spec:
      {{ if not .Values.use_preset }}
      volumes:
      - name: ca-trust
        configMap:
          name: ca-trust
          defaultMode: 420
      {{ end }}
      containers:
        - name: product-service
          image: ' '
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          env:
            - name: RATING_URL
              value: "https://rating-{{ .Release.Namespace }}.apps.{{ .Values.route_hostname }}"
          {{ if not .Values.use_preset }}
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          volumeMounts:
            - name: ca-trust
              mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
              subPath: ca-bundle.crt
          {{ end }}
          