kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: product-service
    app.kubernetes.io/component: product-service
    app.kubernetes.io/instance: product-service
    app.kubernetes.io/part-of: product-service-app
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/cloudfirst/product-service:latest'
      generation: 2
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local